### ISSUE TITLE
WMLJobImpl.updateStatus() has input file data in the response

### ISSUE THREAD

**Issue by jrobichaud** [achabrier/assets#2]
WMLJobImpl.updateStatus() calls 

`String res = doGet(url + "/v4/jobs/" + job_id, headers);` to update its status.

Which contains ultimately the input data in the response:

![image](https://user-images.githubusercontent.com/12142702/83139281-1c74cf80-a0ba-11ea-8995-a0dfe9989436.png)

In the case of inline jobs it represents a lot of data in each response and this data is not useful in most cases. It could be a reference url to this data or something.

**Comment by achabrier** [comment]
Hi, I am moving the DO for WML for Java to  https://github.com/IBMDecisionOptimization/DOforWMLwithJava

I agree with you, we have a parameter to not get the input back. Will sahre with you.

**Comment by jrobichaud** [comment]
You will move the issue there?

**Comment by achabrier** [comment]
I do not find how to do, could you recreate your issue on 
https://github.com/IBMDecisionOptimization/DOforWMLwithJava ?

**Comment by jrobichaud** [comment]
The issue is moved to https://github.com/IBMDecisionOptimization/DOforWMLwithJava/issues/1
